### ISSUE TITLE
This module is worthless

### ISSUE THREAD

**Issue by Dillybob92** [nodejitsu/node-http-proxy#1006]
If it doesn't have some sort of rate limiting feature implemented. Which nginx, and haproxy have.

**Comment by acanimal** [comment]
IMO http-proxy is extremely flexibly. Adding a rate limiter is as easy as integrate any node module that implements a rate limiter and checks your requests before sending to http-proxy.

**Comment by jcrugzz** [comment]
Im sorry you think a missing feature equates to the module being useless. This module is meant to be a building block not a "do it all" nginx/haproxy replacement. @acanimal has the right idea :).

**Comment by colbyn** [comment]
Immediately after reading this `https://runcommand.io/2016/06/26/my-condolences-youre-now-the-maintainer-of-a-popular-open-source-project/` I though it was funny seeing this ticket lol

**Comment by indexzero** [comment]
@Dillybob92 next time, dig deep and try to find some basic human empathy. Starting a conversation with an inflammatory and insulting title like "This module is worthless" only hurts. [Why do that?](https://speakerdeck.com/indexzero/keeping-important-code-alive-seattlejs-march-2015)

I am locking this issue. @jcrugzz we should use this as an opportunity to adopt a code of conduct since this kind of behavior is obviously not welcome.
