### ISSUE TITLE
Changing the case of proxied headers breaks poorly written clients

### ISSUE THREAD

**Issue by timmattison** [nodejitsu/node-http-proxy#40]
I am working with a system that is very sensitive, against the standards, to the case of headers that are passed back to it.  The current code in node-http-proxy takes all of the headers (ie. "Content-Type") and converts them to lower case.  I know that the client is behaving badly here but it would be nice to have this configurable.  I will see if I can code this up and send a pull request.

In the meantime, is there a way to disable this behavior?

**Comment by djskinner** [comment]
Is there a way to 'fix' headers on a proxyReq event? I have the same problem where the server I am connecting to cares about the case sensitivity of the headers so need to correct node's tampering.

@d11wtq did you ever find out where the original header names were store? It would be good if I could get node-http-proxy to forward the original case-preserved headers rather than it using the lower-cased versions from node.

**Comment by djskinner** [comment]
For anyone who comes across this thread as I did, I created a fork that forwards on the raw headers to the target rather than the ones that node has modified.

https://github.com/djskinner/node-http-proxy/commit/8a7b44b5e8cbb9f11e0c773fb069d3ab53b82cd6

**Comment by mixxen** [comment]
djskinners modification should be applied when ```preserveHeaderKeyCase``` is set to ```true```
