### ISSUE TITLE
Retry on certain errors

### ISSUE THREAD

**Issue by TrevorBurnham** [nodejitsu/node-http-proxy#426]
I'd like to send the request again when the server being proxied exhibit certain behaviors. Is this possible? I've tried doing this:

```
proxy.on('proxyError', function(err, req, res) {
  if (err.code === 'ECONNREFUSED') {
    process.nextTick(function() {
      proxy.proxyRequest(req, res, proxyOptions);
    });
  }
});
```

But, this doesn't appear to send the request to the server again, and no response is ever given to the client.

**Comment by wmertens** [comment]
@TrevorBurnham did you ever fix this? I want to make a small proxy that holds requests while the service process restarts…

**Comment by TrevorBurnham** [comment]
@wmertens Not sure. I’m no longer working on that proxy project.

**Comment by wmertens** [comment]
Ok, this is a backburner issue, but when I get around to it I'll update here

**Comment by julienvincent** [comment]
I know this is a really old issue, but I am running into this same problem. @wmertens I have exactly the same use-case as you - did you ever solve this?

**Comment by wmertens** [comment]
no not yet.

In fact I'm so enamoured by HTTP/2 that I'll be skipping nginx and instead use haproxy for SSL offload and use fastify to talk HTTP/2 directly with the browsers. I do believe I can configure HAProxy to hold connections until a server responds.

That way each client only uses a single TCP connection, I get cheap Server Sent Events, with only one session lookup per connection. With websockets it's a lot more complex to do stateful sessions.

Anyway, not there yet.

**Comment by johndevedu** [comment]
I also wanted to use the proxy to gracefully retry while server restarted. Since http-proxy did not have the retry capability built in,  I came up with a solution where I use a simple ping mechanism using a http tool (http module, axios, etc). I built the retry mechanism (recursive ping w/ timeout) using http. When it came back status 200, then I would proxy the request. Extra unnecessary ping, but since it's all localhost for me, I don't take a perf hit. Hope this idea helps someone.
