### ISSUE TITLE
"Direct IP access not allowed" when reverse proxying to CloudFlare domain

### ISSUE THREAD

**Issue by requiredfield** [nodejitsu/node-http-proxy#779]
The following code successfully creates a reverse proxy server on localhost:8000 which reverse proxies to httpbin.org:
```js
var httpProxy = require('http-proxy');
httpProxy.createProxyServer({target: 'http://httpbin.org'}).listen(8000);
```
However, if you change http://httpbin.org to any CloudFlare-enabled site (including http://www.cloudflare.com itself), you get "Error 1003 Direct IP access not allowed". Is there some way to configure the proxy server so it can successfully front CloudFlare-enabled sites? Sorry if I'm missing something obvious.

**Comment by requiredfield** [comment]
Never mind, seem to have figured it out:
```js
httpProxy.createServer({changeOrigin: true, target: 'http://www.cloudflare.com'}).listen(8000);
```

**Comment by masasidan** [comment]
Hey, I know it's been 5 years, But it's somehow directing me to the URL instead of staying on the proxy.
Weird. Do you have any idea why?

**Comment by adamchipperfield** [comment]
I'm getting the same as @idanii...

**Comment by piyushkmr** [comment]
I think it might be due to http->https redirection.
If you are proxying in this way myserver->HTTP://external-server.
And external server is configured to auto forward HTTP to https, then it will return https://external-server in its location-header.
Now you browser will 301 to https://external-server
