### ISSUE TITLE
Proper way to replay HTTP request

### ISSUE THREAD

**Issue by h2non** [nodejitsu/node-http-proxy#846]
I would like to replay a some HTTP incoming request in background. 
I believe that a possible fit for this could be creating a new `net.Socket` to avoid collision between the forwarded request and the replayed one.

Here is an example code:
```js
var http = require('http'),
    httpProxy = require('http-proxy');

var proxy = httpProxy.createProxyServer({});
var server = http.createServer(function(req, res) {
  // Normal forward
  proxy.web(req, res, { target: 'http://127.0.0.1:5060' });
  // Replay it (but forget about the response)
  var newRes = new http.ServerResponse(req)
  proxy.web(req, newRes, { target: 'http://127.0.0.1:6060' });
});

console.log("listening on port 5050")
server.listen(5050);
```

Any possible idea about how to achieve this in a reliable way?

**Comment by DesignByOnyx** [comment]
Your code should work as you have it written, however there will be no feedback to the user if the replayed request doesn't work. If the replayed request causes an error it could put your app in a bad state. Using this module might not suit your use case because this module will automatically resolve the response (as a proxy should). However, it's pretty easy to proxy a request manually (without this module). You can add your own custom logic however you see fit. You can kick off two separate requests and when both are done you can call `res.end()` with your custom response.

```javascript
var server = http.createServer(function(req, res) {
  // see https://nodejs.org/api/http.html#http_http_request_options_callback
  var responseReceived = false,
      replayDone = false;

  function sendResponse () {
    if (replayDone && responseReceived) {
      res.end( ... );
    }
  }

  // proxy
  http.request({
    host: 123.456.78.90
    port: 9000,
    method: req.method,
    path: req.url,
    headers: req.headers
  }, function (proxyRes) {
    responseReceived = true;
    sendResponse();
  }).end();

  // replay
  http.request({
    host: 98.76.543.210
    port: 7000,
    method: req.method,
    path: req.url,
    headers: req.headers
  }, function (proxyRes) {
    replayDone = true;
    sendResponse();
  }).end();

});
```

**Comment by h2non** [comment]
Thanks! I already solved this using a similar approach ([code here](https://github.com/h2non/rocky/blob/develop/lib/replay.js#L50)).

Also I'm using the [setupOutgoing](https://github.com/nodejitsu/node-http-proxy/blob/master/lib/http-proxy/common.js#L33) function like http-proxy does.

The challenge here is about avoiding side-effects with the duplex net socket stream of the original request and response, since it only could be used from the initial request instead of the replayed one.

I believe that this is clear and solved from my side. Closing.
